FROM python:3.11-slim
WORKDIR /workspace

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy only requirements
COPY etl/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Default CMD for dev
CMD ["python", "etl/app/pipeline.py"]

